site_name: Ma vie publique
docs_dir: ./resume/
repo_url: https://my.cyber-neurones.org/
site_author: ARIAS FREDERIC
site_description: Test de conversion Markdown vers Site

nav:
  - Introduction : README.md
  - Experiences professionnelles : PROFESSION/README.md  
  - Salon : SALON/README.md  
  - Formation : FORMATION/README.md
  - Linux : 
    - General : LINUX/README.md
    - Ubuntu : UBUNTU/README.md
    - Debian : DEBIAN/README.md
    - Raspbian : RASPBIAN/README.md
    - Serveur : SERVEUR/README.md
  - Quelques dev : DEV/README.md     
  - Compétitions sportives : 
    - Liste : COMPETITIONS/README.md
        - Resultat ITRA : ITRA/README.md  
        - Resultat FFA : FFA/README.md 
  - Trekking : TREKKING/README.md
  - Canyonning / Via Ferrata : MONTAGNE/README.md
  - Velo : VELO/README.md   
  - Autres sports : SPORT/README.md     
  - Les logiciels que j'aime : APP/README.md
  - Le harware que j'aime : HARDWARE/README.md
  - Biot, le village : BIOT/README.md   
  - Autre : AUTRE/README.md  
  - HUGO, tentative migration : HUGO/README.md   
  - MKDOCS, tentative migration : MKDOCS/README.md  

theme:
    name: readthedocs
    sticky_navigation: true
    features:
        - navigation.instant
        - navigation.sections
    custom_dir: overrides 
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    nav_style: dark
    locale: fr
    include_homepage_in_sidebar: true
    collapse_navigation: true
    titles_only: false
    navigation_depth: 5 

markdown_extensions:
  - admonition
  - markdown.extensions.toc:
      baselevel: 2
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - def_list
  - pymdownx.tasklist
  - pymdownx.details
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - css/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

plugins:
  - search

extra:
  social:
    - link: http://fr.linkedin.com/in/ariasfrederic

copyright: Copyright &copy; 2023 ARIAS Frederic


